/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v7.0
processor: MIMXRT1064xxxxA
package_id: MIMXRT1064DVL6A
mcu_data: ksdk2_0
processor_version: 7.0.1
board: MIMXRT1064-EVK
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 807635b5-074f-4250-b1e8-d8001ebce3f1
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'msg'
- type_id: 'msg_6e2baaf3b97dbeef01c0043275f9a0e7'
- global_messages: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DCP initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DCP'
- type: 'dcp'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'dcp_95a1068fdf77eaec189146622e54f5e0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DCP'
- config_sets:
  - config_general:
    - settings_common:
      - setting_gatherResidualWrites: 'true'
      - setting_enableContextCaching: 'false'
      - setting_enableContextSwitching: 'true'
      - setting_enableChannel: 'kDCP_ch0Enable'
    - settings_interrupt:
      - setting_enableChannelInterrupt: ''
      - setting_interrupt_channel0:
        - IRQn: 'DCP_VMI_IRQn'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - setting_interrupt:
        - IRQn: 'DCP_IRQn'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
  - config_handles:
    - settings_handles:
      - 0:
        - handlerId: 'handle_0'
        - channel: 'kDCP_Channel0'
        - keySlot: 'kDCP_KeySlot0'
        - swapConfig: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const dcp_config_t DCP_config = {
  .gatherResidualWrites = true,
  .enableContextCaching = false,
  .enableContextSwitching = true,
  .enableChannel = kDCP_ch0Enable,
  .enableChannelInterrupt = kDCP_chIntDisable,
};
const dcp_handle_t DCP_handle_0 = {
  .channel = kDCP_Channel0,
  .keySlot = kDCP_KeySlot0,
  .swapConfig = kDCP_NoSwap,
};

void DCP_init(void) {
  /* Initialize DCP. */
  DCP_Init(DCP_PERIPHERAL, &DCP_config);
}

/***********************************************************************************************************************
 * GPT2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPT2'
- type: 'gpt'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'gpt_e92a0cbd07e389b82a1d19b05eb9fdda'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPT2'
- config_sets:
  - fsl_gpt:
    - gpt_config:
      - clockSource: 'kGPT_ClockSource_Periph'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - oscDivider: '1'
      - divider: '75'
      - enableFreeRun: 'false'
      - enableRunInWait: 'true'
      - enableRunInStop: 'false'
      - enableRunInDoze: 'false'
      - enableRunInDbg: 'false'
      - enableMode: 'true'
    - input_capture_channels: []
    - output_compare_channels:
      - 0:
        - channel: 'kGPT_OutputCompare_Channel1'
        - mode: 'kGPT_OutputOperation_Disconnected'
        - compare_value_str: '1ms'
    - interrupt_requests: 'kGPT_OutputCompare1InterruptEnable'
    - isInterruptEnabled: 'true'
    - interrupt:
      - IRQn: 'GPT2_IRQn'
      - enable_priority: 'true'
      - priority: '6'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const gpt_config_t GPT2_config = {
  .clockSource = kGPT_ClockSource_Periph,
  .divider = 75,
  .enableFreeRun = false,
  .enableRunInWait = true,
  .enableRunInStop = false,
  .enableRunInDoze = false,
  .enableRunInDbg = false,
  .enableMode = true
};

void GPT2_init(void) {
  /* GPT device and channels initialization */
  GPT_Init(GPT2_PERIPHERAL, &GPT2_config);
  GPT_SetOscClockDivider(GPT2_PERIPHERAL, 1);
  GPT_SetOutputCompareValue(GPT2_PERIPHERAL, kGPT_OutputCompare_Channel1, 1000);
  GPT_SetOutputOperationMode(GPT2_PERIPHERAL, kGPT_OutputCompare_Channel1, kGPT_OutputOperation_Disconnected);
  /* Enable GPT interrupt sources */
  GPT_EnableInterrupts(GPT2_PERIPHERAL, kGPT_OutputCompare1InterruptEnable);
  /* Interrupt vector GPT2_IRQn priority settings in the NVIC */
  NVIC_SetPriority(GPT2_GPT_IRQN, GPT2_GPT_IRQ_PRIORITY);
  /* Enable interrupt GPT2_IRQn request in the NVIC */
  EnableIRQ(GPT2_GPT_IRQN);
  /* Start the GPT timer */ 
  GPT_StartTimer(GPT2_PERIPHERAL);
}

/***********************************************************************************************************************
 * PulseEncoder initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PulseEncoder'
- type: 'qtmr'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'qtmr_460dd7aa3f3371843c2548acd54252b0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TMR1'
- config_sets:
  - fsl_qtmr:
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - qtmr_channels:
      - 0:
        - channel_prefix_id: 'Channel_0'
        - channel: 'kQTMR_Channel_0'
        - primarySource: 'kQTMR_ClockCounter0InputPin'
        - primarySourceFreq: '1'
        - secondarySource: 'kQTMR_Counter1InputPin'
        - countingMode: 'kQTMR_PriSrcRiseEdgeSecDir'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'inputCapture'
        - inputCaptureMode:
          - inputPolarity: 'false'
          - reloadOnCapture: 'false'
          - captureMode: 'kQTMR_NoCapture'
        - dmaIntMode: 'polling'
      - 1:
        - channel_prefix_id: 'Channel_2'
        - channel: 'kQTMR_Channel_2'
        - primarySource: 'kQTMR_ClockCounter2InputPin'
        - primarySourceFreq: '10'
        - secondarySource: 'kQTMR_Counter3InputPin'
        - countingMode: 'kQTMR_PriSrcRiseEdgeSecDir'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'inputCapture'
        - inputCaptureMode:
          - inputPolarity: 'false'
          - reloadOnCapture: 'false'
          - captureMode: 'kQTMR_NoCapture'
        - dmaIntMode: 'polling'
    - interruptVector:
      - enable_irq: 'false'
      - interrupt:
        - IRQn: 'TMR1_IRQn'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const qtmr_config_t PulseEncoder_Channel_0_config = {
  .primarySource = kQTMR_ClockCounter0InputPin,
  .secondarySource = kQTMR_Counter1InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};
const qtmr_config_t PulseEncoder_Channel_2_config = {
  .primarySource = kQTMR_ClockCounter2InputPin,
  .secondarySource = kQTMR_Counter3InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};

void PulseEncoder_init(void) {
  /* Quad timer channel Channel_0 peripheral initialization */
  QTMR_Init(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_0_CHANNEL, &PulseEncoder_Channel_0_config);
  /* Setup the Input capture mode of the timer channel */
  QTMR_SetupInputCapture(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_0_CHANNEL, kQTMR_Counter1InputPin, false, false, kQTMR_NoCapture);
  /* Quad timer channel Channel_2 peripheral initialization */
  QTMR_Init(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_2_CHANNEL, &PulseEncoder_Channel_2_config);
  /* Setup the Input capture mode of the timer channel */
  QTMR_SetupInputCapture(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_2_CHANNEL, kQTMR_Counter3InputPin, false, false, kQTMR_NoCapture);
  /* Start the timer - select the timer counting mode */
  QTMR_StartTimer(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_0_CHANNEL, kQTMR_PriSrcRiseEdgeSecDir);
  /* Start the timer - select the timer counting mode */
  QTMR_StartTimer(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_2_CHANNEL, kQTMR_PriSrcRiseEdgeSecDir);
}

/***********************************************************************************************************************
 * TEMPMON initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TEMPMON'
- type: 'tempmon'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'tempmon_c966e400757748d37785414258f2801c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TEMPMON'
- config_sets:
  - fsl_tempmon:
    - tempmon_config:
      - singleMeasurement: 'false'
      - clock_config:
        - clockSource: 'LowFreqClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
      - frequencySet: '65535'
      - lowAlarmTemp: '39'
      - highAlarmTemp: '44'
      - panicAlarmTemp: '90'
    - startMeasure: 'true'
    - interruptsCfg:
      - isInterruptEnabledLowHigh: 'false'
      - interruptLowHigh:
        - IRQn: 'TEMP_LOW_HIGH_IRQn'
        - enable_priority: 'true'
        - priority: '0'
        - enable_custom_name: 'false'
      - isInterruptEnabledPanic: 'false'
      - interruptPanic:
        - IRQn: 'TEMP_PANIC_IRQn'
        - enable_priority: 'true'
        - priority: '1'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const tempmon_config_t TEMPMON_config = {
  .frequency = 65535,
  .lowAlarmTemp = 39,
  .highAlarmTemp = 44,
  .panicAlarmTemp = 90
};

void TEMPMON_init(void) {
  /* TEMPMON initialization */
  TEMPMON_Init(TEMPMON_PERIPHERAL, &TEMPMON_config);
  /* Start measure */
  TEMPMON_StartMeasure(TEMPMON_PERIPHERAL);
}

/***********************************************************************************************************************
 * TMR2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TMR2'
- type: 'qtmr'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'qtmr_460dd7aa3f3371843c2548acd54252b0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TMR2'
- config_sets:
  - fsl_qtmr:
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - qtmr_channels:
      - 0:
        - channel_prefix_id: 'Channel_3'
        - channel: 'kQTMR_Channel_3'
        - primarySource: 'kQTMR_ClockDivide_8'
        - secondarySource: 'kQTMR_Counter3InputPin'
        - countingMode: 'kQTMR_PriSrcRiseEdge'
        - enableMasterMode: 'true'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'pwmOutput'
        - pwmMode:
          - freq_value_str: '1kHz'
          - dutyCyclePercent: '0'
          - outputPolarity: 'false'
        - dmaIntMode: 'polling'
    - interruptVector:
      - enable_irq: 'false'
      - interrupt:
        - IRQn: 'TMR2_IRQn'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const qtmr_config_t TMR2_Channel_3_config = {
  .primarySource = kQTMR_ClockDivide_8,
  .secondarySource = kQTMR_Counter3InputPin,
  .enableMasterMode = true,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};

void TMR2_init(void) {
  /* Quad timer channel Channel_3 peripheral initialization */
  QTMR_Init(TMR2_PERIPHERAL, TMR2_CHANNEL_3_CHANNEL, &TMR2_Channel_3_config);
  /* Setup the PWM mode of the timer channel */
  QTMR_SetupPwm(TMR2_PERIPHERAL, TMR2_CHANNEL_3_CHANNEL, 1000UL, 0U, false, TMR2_CHANNEL_3_CLOCK_SOURCE);
  /* Start the timer - select the timer counting mode */
  QTMR_StartTimer(TMR2_PERIPHERAL, TMR2_CHANNEL_3_CHANNEL, kQTMR_PriSrcRiseEdge);
}

/***********************************************************************************************************************
 * communicate initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'communicate'
- type: 'lpuart'
- mode: 'transfer'
- custom_name_enabled: 'true'
- type_id: 'lpuart_54a65a580e3462acdbacefd5299e0cac'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART5'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '460800'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourceMatchResult'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter2'
      - enableTx: 'true'
      - enableRx: 'true'
  - transferCfg:
    - transfer:
      - init_rx_transfer: 'true'
      - rx_transfer:
        - data_size: '20'
      - init_tx_transfer: 'true'
      - tx_transfer:
        - data_size: '20'
      - init_callback: 'true'
      - callback_fcn: 'com_callback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t communicate_config = {
  .baudRate_Bps = 460800,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0,
  .rxFifoWatermark = 1,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourceMatchResult,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter2,
  .enableTx = true,
  .enableRx = true
};
lpuart_handle_t communicate_handle;
uint8_t communicate_rxBuffer[COMMUNICATE_RX_BUFFER_SIZE];
const lpuart_transfer_t communicate_rxTransfer = {
  .data = communicate_rxBuffer,
  .dataSize = COMMUNICATE_RX_BUFFER_SIZE
};
uint8_t communicate_txBuffer[COMMUNICATE_TX_BUFFER_SIZE];
const lpuart_transfer_t communicate_txTransfer = {
  .data = communicate_txBuffer,
  .dataSize = COMMUNICATE_TX_BUFFER_SIZE
};

void communicate_init(void) {
  LPUART_Init(COMMUNICATE_PERIPHERAL, &communicate_config, COMMUNICATE_CLOCK_SOURCE);
  LPUART_TransferCreateHandle(COMMUNICATE_PERIPHERAL, &communicate_handle, com_callback, NULL);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  DCP_init();
  GPT2_init();
  PulseEncoder_init();
  TEMPMON_init();
  TMR2_init();
  communicate_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
