/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v8.0
processor: MIMXRT1064xxxxA
package_id: MIMXRT1064DVL6A
mcu_data: ksdk2_0
processor_version: 8.0.1
board: MIMXRT1064-EVK
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 807635b5-074f-4250-b1e8-d8001ebce3f1
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'edma_6d0dd4e17e2f179c7d42d98767129ede'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'true'
      - enableRoundRobinArbitration: 'false'
      - enableDebugMode: 'false'
    - dma_table: []
    - edma_channels: []
    - errInterruptConfig:
      - enableErrInterrupt: 'false'
      - errorInterrupt:
        - IRQn: 'DMA_ERROR_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t DMA0_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = true,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = false
};

void DMA0_init(void) {
}

/***********************************************************************************************************************
 * BAT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'BAT'
- type: 'adc_12b1msps_sar'
- mode: 'ADC_GENERAL'
- custom_name_enabled: 'true'
- type_id: 'adc_12b1msps_sar_6a490e886349a7b2b07bed10ce7b299b'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC1'
- config_sets:
  - fsl_adc:
    - clockConfig:
      - clockSource: 'kADC_ClockSourceAD'
      - clockSourceFreq: 'custom:10 MHz'
      - clockDriver: 'kADC_ClockDriver8'
      - samplePeriodMode: 'kADC_SamplePeriodLong24Clcoks'
      - enableAsynchronousClockOutput: 'true'
    - conversionConfig:
      - resolution: 'kADC_Resolution12Bit'
      - hardwareAverageMode: 'kADC_HardwareAverageCount32'
      - enableHardwareTrigger: 'software'
      - enableHighSpeed: 'false'
      - enableLowPower: 'false'
      - enableContinuousConversion: 'false'
      - enableOverWrite: 'true'
      - enableDma: 'false'
    - resultingTime: []
    - resultCorrection:
      - doAutoCalibration: 'true'
      - offset: '0'
    - hardwareCompareConfiguration:
      - hardwareCompareMode: 'disabled'
      - value1: '0'
      - value2: '0'
    - enableInterrupt: 'true'
    - adc_interrupt:
      - IRQn: 'ADC1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '6'
      - enable_custom_name: 'false'
    - adc_channels_config:
      - 0:
        - channelNumber: 'IN.9'
        - channelName: 'BAT'
        - channelGroup: '0'
        - initializeChannel: 'true'
        - enableInterruptOnConversionCompleted: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t BAT_config = {
  .enableOverWrite = true,
  .enableContinuousConversion = false,
  .enableHighSpeed = false,
  .enableLowPower = false,
  .enableLongSample = true,
  .enableAsynchronousClockOutput = true,
  .referenceVoltageSource = kADC_ReferenceVoltageSourceAlt0,
  .samplePeriodMode = kADC_SamplePeriodLong24Clcoks,
  .clockSource = kADC_ClockSourceAD,
  .clockDriver = kADC_ClockDriver8,
  .resolution = kADC_Resolution12Bit
};
const adc_channel_config_t BAT_channels_config[1] = {
  {
    .channelNumber = BAT,
    .enableInterruptOnConversionCompleted = true
  }
};
void BAT_init(void) {
  /* Initialize ADC1 peripheral. */
  ADC_Init(BAT_PERIPHERAL, &BAT_config);
  /* Configure ADC1 peripheral to average 32 conversions in one measurement. */
  ADC_SetHardwareAverageConfig(BAT_PERIPHERAL, kADC_HardwareAverageCount32);
  /* Perform ADC1 auto calibration. */
  ADC_DoAutoCalibration(BAT_PERIPHERAL);
  /* Initialize ADC1 channel 9. */
  ADC_SetChannelConfig(BAT_PERIPHERAL, 0U, &BAT_channels_config[0]);
  /* Enable interrupt ADC1_IRQn request in the NVIC. */
  EnableIRQ(BAT_IRQN);
}

/***********************************************************************************************************************
 * COM initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'COM'
- type: 'lpuart'
- mode: 'transfer'
- custom_name_enabled: 'true'
- type_id: 'lpuart_54a65a580e3462acdbacefd5299e0cac'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART4'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '460800'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter16'
      - enableTx: 'true'
      - enableRx: 'true'
  - transferCfg:
    - transfer:
      - init_rx_transfer: 'true'
      - rx_transfer:
        - data_size: '30'
      - init_tx_transfer: 'false'
      - tx_transfer:
        - data_size: '10'
      - init_callback: 'true'
      - callback_fcn: 'com_callback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t COM_config = {
  .baudRate_Bps = 460800,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0,
  .rxFifoWatermark = 1,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter16,
  .enableTx = true,
  .enableRx = true
};
lpuart_handle_t COM_handle;
uint8_t COM_rxBuffer[COM_RX_BUFFER_SIZE];
const lpuart_transfer_t COM_rxTransfer = {
  .data = COM_rxBuffer,
  .dataSize = COM_RX_BUFFER_SIZE
};

void COM_init(void) {
  LPUART_Init(COM_PERIPHERAL, &COM_config, COM_CLOCK_SOURCE);
  LPUART_TransferCreateHandle(COM_PERIPHERAL, &COM_handle, com_callback, NULL);
}

/***********************************************************************************************************************
 * DebugConsole initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DebugConsole'
- type: 'debug_console'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'debug_console_51864e4f3ac859dae7b603e07bc4ae33'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - fsl_debug_console:
    - config:
      - SDK_DEBUGCONSOLE: 'DEBUGCONSOLE_DISABLE'
      - SDK_DEBUGCONSOLE_UART: 'semihost'
      - DEBUG_CONSOLE_RX_ENABLE: 'true'
      - DEBUG_CONSOLE_PRINTF_MAX_LOG_LEN: '128'
      - DEBUG_CONSOLE_SCANF_MAX_LOG_LEN: '20'
      - DEBUG_CONSOLE_ENABLE_ECHO: 'false'
      - PRINTF_FLOAT_ENABLE: 'false'
      - SCANF_FLOAT_ENABLE: 'false'
      - PRINTF_ADVANCED_ENABLE: 'false'
      - SCANF_ADVANCED_ENABLE: 'false'
      - DEBUG_CONSOLE_TRANSFER_NON_BLOCKING: 'false'
      - DEBUG_CONSOLE_TRANSMIT_BUFFER_LEN: '512'
      - DEBUG_CONSOLE_RECEIVE_BUFFER_LEN: '1024'
      - DEBUG_CONSOLE_TX_RELIABLE_ENABLE: 'true'
      - DEBUG_CONSOLE_DISABLE_RTOS_SYNCHRONIZATION: 'false'
    - debug_console_codegenerator: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

void DebugConsole_init(void) {
}

/***********************************************************************************************************************
 * GPIO1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO1'
- type: 'igpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO1'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'false'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO1_Combined_0_15_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_comb_16_31: 'true'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO1_Combined_16_31_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int0: 'false'
    - gpio_interrupt_int0:
      - IRQn: 'GPIO1_INT0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int1: 'false'
    - gpio_interrupt_int1:
      - IRQn: 'GPIO1_INT1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int2: 'false'
    - gpio_interrupt_int2:
      - IRQn: 'GPIO1_INT2_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int3: 'false'
    - gpio_interrupt_int3:
      - IRQn: 'GPIO1_INT3_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int4: 'false'
    - gpio_interrupt_int4:
      - IRQn: 'GPIO1_INT4_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int5: 'false'
    - gpio_interrupt_int5:
      - IRQn: 'GPIO1_INT5_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int6: 'false'
    - gpio_interrupt_int6:
      - IRQn: 'GPIO1_INT6_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_int7: 'false'
    - gpio_interrupt_int7:
      - IRQn: 'GPIO1_INT7_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

void GPIO1_init(void) {
  /* Make sure, the clock gate for GPIO1 is enabled (e. g. in pin_mux.c) */
  /* Enable interrupt GPIO1_Combined_16_31_IRQn request in the NVIC */
  EnableIRQ(GPIO1_Combined_16_31_IRQn);
}

/***********************************************************************************************************************
 * GPIO3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO3'
- type: 'igpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_b1c1fa279aa7069dca167502b8589cb7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO3'
- config_sets:
  - fsl_gpio:
    - enable_irq_comb_0_15: 'true'
    - gpio_interrupt_comb_0_15:
      - IRQn: 'GPIO3_Combined_0_15_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_comb_16_31: 'false'
    - gpio_interrupt_comb_16_31:
      - IRQn: 'GPIO3_Combined_16_31_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

void GPIO3_init(void) {
  /* Make sure, the clock gate for GPIO3 is enabled (e. g. in pin_mux.c) */
  /* Enable interrupt GPIO3_Combined_0_15_IRQn request in the NVIC */
  EnableIRQ(GPIO3_Combined_0_15_IRQn);
}

/***********************************************************************************************************************
 * PIT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PIT'
- type: 'pit'
- mode: 'LPTMR_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'pit_a4782ba5223c8a2527ba91aeb2bc4159'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PIT'
- config_sets:
  - fsl_pit:
    - enableRunInDebug: 'false'
    - enableSharedInterrupt: 'true'
    - sharedInterrupt:
      - IRQn: 'PIT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '2'
      - enable_custom_name: 'false'
    - timingConfig:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
    - channels:
      - 0:
        - channel_id: 'ENCODER_CH'
        - channelNumber: '0'
        - enableChain: 'false'
        - timerPeriod: '3Ms'
        - startTimer: 'true'
        - enableInterrupt: 'true'
      - 1:
        - channel_id: 'MOTOR_CH'
        - channelNumber: '3'
        - enableChain: 'false'
        - timerPeriod: '6 ms'
        - startTimer: 'true'
        - enableInterrupt: 'true'
      - 2:
        - channel_id: 'STEER_CH'
        - channelNumber: '2'
        - enableChain: 'false'
        - timerPeriod: '10Ms'
        - startTimer: 'true'
        - enableInterrupt: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const pit_config_t PIT_config = {
  .enableRunInDebug = false
};

void PIT_init(void) {
  /* Initialize the PIT. */
  PIT_Init(PIT_PERIPHERAL, &PIT_config);
  /* Set channel 0 period to 3 ms (75000 ticks). */
  PIT_SetTimerPeriod(PIT_PERIPHERAL, PIT_ENCODER_CH, PIT_ENCODER_CH_TICKS);
  /* Set channel 3 period to 6 ms (150000 ticks). */
  PIT_SetTimerPeriod(PIT_PERIPHERAL, PIT_MOTOR_CH, PIT_MOTOR_CH_TICKS);
  /* Set channel 2 period to 10 ms (250000 ticks). */
  PIT_SetTimerPeriod(PIT_PERIPHERAL, PIT_STEER_CH, PIT_STEER_CH_TICKS);
  /* Enable interrupts from channel 0. */
  PIT_EnableInterrupts(PIT_PERIPHERAL, PIT_ENCODER_CH, kPIT_TimerInterruptEnable);
  /* Enable interrupts from channel 3. */
  PIT_EnableInterrupts(PIT_PERIPHERAL, PIT_MOTOR_CH, kPIT_TimerInterruptEnable);
  /* Enable interrupts from channel 2. */
  PIT_EnableInterrupts(PIT_PERIPHERAL, PIT_STEER_CH, kPIT_TimerInterruptEnable);
  /* Interrupt vector PIT_IRQN priority settings in the NVIC */
  NVIC_SetPriority(PIT_IRQN, PIT_IRQ_PRIORITY);
  /* Enable interrupt PIT_IRQN request in the NVIC */
  EnableIRQ(PIT_IRQN);
  /* Start channel 0. */
  PIT_StartTimer(PIT_PERIPHERAL, PIT_ENCODER_CH);
  /* Start channel 3. */
  PIT_StartTimer(PIT_PERIPHERAL, PIT_MOTOR_CH);
  /* Start channel 2. */
  PIT_StartTimer(PIT_PERIPHERAL, PIT_STEER_CH);
}

/***********************************************************************************************************************
 * PulseEncoder initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PulseEncoder'
- type: 'qtmr'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'qtmr_460dd7aa3f3371843c2548acd54252b0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TMR1'
- config_sets:
  - fsl_qtmr:
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - qtmr_channels:
      - 0:
        - channel_prefix_id: 'Channel_0'
        - channel: 'kQTMR_Channel_0'
        - primarySource: 'kQTMR_ClockCounter0InputPin'
        - primarySourceFreq: '1'
        - secondarySource: 'kQTMR_Counter2InputPin'
        - countingMode: 'kQTMR_PriSrcRiseEdgeSecDir'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'inputCapture'
        - inputCaptureMode:
          - inputPolarity: 'false'
          - reloadOnCapture: 'false'
          - captureMode: 'kQTMR_NoCapture'
        - dmaIntMode: 'polling'
      - 1:
        - channel_prefix_id: 'Channel_2'
        - channel: 'kQTMR_Channel_1'
        - primarySource: 'kQTMR_ClockCounter1InputPin'
        - primarySourceFreq: '1'
        - secondarySource: 'kQTMR_Counter3InputPin'
        - countingMode: 'kQTMR_PriSrcRiseEdgeSecDir'
        - enableMasterMode: 'false'
        - enableExternalForce: 'false'
        - faultFilterCount: '3'
        - faultFilterPeriod: '0'
        - debugMode: 'kQTMR_RunNormalInDebug'
        - timerModeInit: 'inputCapture'
        - inputCaptureMode:
          - inputPolarity: 'false'
          - reloadOnCapture: 'false'
          - captureMode: 'kQTMR_NoCapture'
        - dmaIntMode: 'polling'
    - interruptVector:
      - enable_irq: 'false'
      - interrupt:
        - IRQn: 'TMR1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const qtmr_config_t PulseEncoder_Channel_0_config = {
  .primarySource = kQTMR_ClockCounter0InputPin,
  .secondarySource = kQTMR_Counter2InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};
const qtmr_config_t PulseEncoder_Channel_2_config = {
  .primarySource = kQTMR_ClockCounter1InputPin,
  .secondarySource = kQTMR_Counter3InputPin,
  .enableMasterMode = false,
  .enableExternalForce = false,
  .faultFilterCount = 0,
  .faultFilterPeriod = 0,
  .debugMode = kQTMR_RunNormalInDebug
};

void PulseEncoder_init(void) {
  /* Quad timer channel Channel_0 peripheral initialization */
  QTMR_Init(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_0_CHANNEL, &PulseEncoder_Channel_0_config);
  /* Setup the Input capture mode of the timer channel */
  QTMR_SetupInputCapture(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_0_CHANNEL, kQTMR_Counter2InputPin, false, false, kQTMR_NoCapture);
  /* Quad timer channel Channel_2 peripheral initialization */
  QTMR_Init(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_2_CHANNEL, &PulseEncoder_Channel_2_config);
  /* Setup the Input capture mode of the timer channel */
  QTMR_SetupInputCapture(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_2_CHANNEL, kQTMR_Counter3InputPin, false, false, kQTMR_NoCapture);
  /* Start the timer - select the timer counting mode */
  QTMR_StartTimer(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_0_CHANNEL, kQTMR_PriSrcRiseEdgeSecDir);
  /* Start the timer - select the timer counting mode */
  QTMR_StartTimer(PULSEENCODER_PERIPHERAL, PULSEENCODER_CHANNEL_2_CHANNEL, kQTMR_PriSrcRiseEdgeSecDir);
}

/***********************************************************************************************************************
 * SLAVE initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SLAVE'
- type: 'lpuart'
- mode: 'transfer'
- custom_name_enabled: 'true'
- type_id: 'lpuart_54a65a580e3462acdbacefd5299e0cac'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART8'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '1000000'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '0'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
  - transferCfg:
    - transfer:
      - init_rx_transfer: 'true'
      - rx_transfer:
        - data_size: '30'
      - init_tx_transfer: 'true'
      - tx_transfer:
        - data_size: '1'
      - init_callback: 'true'
      - callback_fcn: 'SlaveCallback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t SLAVE_config = {
  .baudRate_Bps = 1000000,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0,
  .rxFifoWatermark = 0,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};
lpuart_handle_t SLAVE_handle;
uint8_t SLAVE_rxBuffer[SLAVE_RX_BUFFER_SIZE];
const lpuart_transfer_t SLAVE_rxTransfer = {
  .data = SLAVE_rxBuffer,
  .dataSize = SLAVE_RX_BUFFER_SIZE
};
uint8_t SLAVE_txBuffer[SLAVE_TX_BUFFER_SIZE];
const lpuart_transfer_t SLAVE_txTransfer = {
  .data = SLAVE_txBuffer,
  .dataSize = SLAVE_TX_BUFFER_SIZE
};

void SLAVE_init(void) {
  LPUART_Init(SLAVE_PERIPHERAL, &SLAVE_config, SLAVE_CLOCK_SOURCE);
  LPUART_TransferCreateHandle(SLAVE_PERIPHERAL, &SLAVE_handle, SlaveCallback, NULL);
}

/***********************************************************************************************************************
 * SoftTimer initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SoftTimer'
- type: 'gpt'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'gpt_e92a0cbd07e389b82a1d19b05eb9fdda'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPT2'
- config_sets:
  - fsl_gpt:
    - gpt_config:
      - clockSource: 'kGPT_ClockSource_Periph'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - oscDivider: '1'
      - divider: '1'
      - enableFreeRun: 'false'
      - enableRunInWait: 'false'
      - enableRunInStop: 'false'
      - enableRunInDoze: 'false'
      - enableRunInDbg: 'false'
      - enableMode: 'true'
    - input_capture_channels: []
    - output_compare_channels:
      - 0:
        - channel: 'kGPT_OutputCompare_Channel1'
        - mode: 'kGPT_OutputOperation_Disconnected'
        - compare_value_str: '1ms'
    - interrupt_requests: 'kGPT_OutputCompare1InterruptEnable'
    - isInterruptEnabled: 'true'
    - interrupt:
      - IRQn: 'GPT2_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const gpt_config_t SoftTimer_config = {
  .clockSource = kGPT_ClockSource_Periph,
  .divider = 1,
  .enableFreeRun = false,
  .enableRunInWait = false,
  .enableRunInStop = false,
  .enableRunInDoze = false,
  .enableRunInDbg = false,
  .enableMode = true
};

void SoftTimer_init(void) {
  /* GPT device and channels initialization */
  GPT_Init(SOFTTIMER_PERIPHERAL, &SoftTimer_config);
  GPT_SetOscClockDivider(SOFTTIMER_PERIPHERAL, 1);
  GPT_SetOutputCompareValue(SOFTTIMER_PERIPHERAL, kGPT_OutputCompare_Channel1, 25000);
  GPT_SetOutputOperationMode(SOFTTIMER_PERIPHERAL, kGPT_OutputCompare_Channel1, kGPT_OutputOperation_Disconnected);
  /* Enable GPT interrupt sources */
  GPT_EnableInterrupts(SOFTTIMER_PERIPHERAL, kGPT_OutputCompare1InterruptEnable);
  /* Enable interrupt GPT2_IRQn request in the NVIC. */
  EnableIRQ(SOFTTIMER_GPT_IRQN);
  /* Start the GPT timer */ 
  GPT_StartTimer(SOFTTIMER_PERIPHERAL);
}

/***********************************************************************************************************************
 * TEMPMON initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TEMPMON'
- type: 'tempmon'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'tempmon_c966e400757748d37785414258f2801c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TEMPMON'
- config_sets:
  - fsl_tempmon:
    - tempmon_config:
      - singleMeasurement: 'false'
      - clock_config:
        - clockSource: 'LowFreqClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
      - frequencySet: '65535'
      - lowAlarmTemp: '39'
      - highAlarmTemp: '44'
      - panicAlarmTemp: '90'
    - startMeasure: 'true'
    - interruptsCfg:
      - isInterruptEnabledLowHigh: 'false'
      - interruptLowHigh:
        - IRQn: 'TEMP_LOW_HIGH_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'true'
        - priority: '0'
        - enable_custom_name: 'false'
      - isInterruptEnabledPanic: 'false'
      - interruptPanic:
        - IRQn: 'TEMP_PANIC_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'true'
        - priority: '1'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const tempmon_config_t TEMPMON_config = {
  .frequency = 65535,
  .lowAlarmTemp = 39,
  .highAlarmTemp = 44,
  .panicAlarmTemp = 90
};

void TEMPMON_init(void) {
  /* TEMPMON initialization */
  TEMPMON_Init(TEMPMON_PERIPHERAL, &TEMPMON_config);
  /* Start measure */
  TEMPMON_StartMeasure(TEMPMON_PERIPHERAL);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMAMUX_Init(DMA0_DMAMUX_BASEADDR);
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);

  /* Initialize components */
  DMA0_init();
  BAT_init();
  COM_init();
  DebugConsole_init();
  GPIO1_init();
  GPIO3_init();
  PIT_init();
  PulseEncoder_init();
  SLAVE_init();
  SoftTimer_init();
  TEMPMON_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
