/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_SD_B1_04 (coord P2), HAL */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HAL2_GPIO                                           GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_HAL2_GPIO_PIN                                          4U   /*!< GPIO pin number */
#define BOARD_INITPINS_HAL2_GPIO_PIN_MASK                             (1U << 4U)   /*!< GPIO pin mask */

/* GPIO_AD_B1_02 (coord L11), KEY */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K_BACK_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K_BACK_GPIO_PIN                                       18U   /*!< GPIO pin number */
#define BOARD_INITPINS_K_BACK_GPIO_PIN_MASK                          (1U << 18U)   /*!< GPIO pin mask */

/* GPIO_AD_B1_03 (coord M12), KEY */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K_LEFT_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K_LEFT_GPIO_PIN                                       19U   /*!< GPIO pin number */
#define BOARD_INITPINS_K_LEFT_GPIO_PIN_MASK                          (1U << 19U)   /*!< GPIO pin mask */

/* GPIO_AD_B0_01 (coord H10), KEY */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K_RIGHT_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K_RIGHT_GPIO_PIN                                       1U   /*!< GPIO pin number */
#define BOARD_INITPINS_K_RIGHT_GPIO_PIN_MASK                          (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_AD_B0_03 (coord G11), KEY */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K_UP_GPIO                                           GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K_UP_GPIO_PIN                                          3U   /*!< GPIO pin number */
#define BOARD_INITPINS_K_UP_GPIO_PIN_MASK                             (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_AD_B0_15 (coord L10), KEY */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K_OK_GPIO                                           GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K_OK_GPIO_PIN                                         15U   /*!< GPIO pin number */
#define BOARD_INITPINS_K_OK_GPIO_PIN_MASK                            (1U << 15U)   /*!< GPIO pin mask */

/* GPIO_AD_B0_14 (coord H14), KEY */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K_DOWN_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_K_DOWN_GPIO_PIN                                       14U   /*!< GPIO pin number */
#define BOARD_INITPINS_K_DOWN_GPIO_PIN_MASK                          (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_01 (coord M5), COM */

/* GPIO_SD_B1_00 (coord L5), COM */

/* GPIO_B0_00 (coord D7), LSB */

/* GPIO_B0_01 (coord E7), LSB */

/* GPIO_B0_02 (coord E8), DIR */

/* GPIO_B1_08 (coord A12), DIR */

/* GPIO_AD_B1_10 (coord L13), K66 */

/* GPIO_AD_B1_11 (coord J13), K66 */

/* GPIO_AD_B1_15 (coord J14), MOTOR */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIRECT_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DIRECT_GPIO_PIN                                       31U   /*!< GPIO pin number */
#define BOARD_INITPINS_DIRECT_GPIO_PIN_MASK                          (1U << 31U)   /*!< GPIO pin mask */

/* GPIO_AD_B0_10 (coord G13), MOTOR */

/* GPIO_AD_B0_11 (coord G10), MOTOR */

/* GPIO_B1_15 (coord B14), MOTOR */

/* GPIO_B1_11 (coord C13), OLED */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DC_GPIO                                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DC_GPIO_PIN                                           27U   /*!< GPIO pin number */
#define BOARD_INITPINS_DC_GPIO_PIN_MASK                              (1U << 27U)   /*!< GPIO pin mask */

/* GPIO_B1_12 (coord D13), OLED */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RES_GPIO                                            GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RES_GPIO_PIN                                          28U   /*!< GPIO pin number */
#define BOARD_INITPINS_RES_GPIO_PIN_MASK                             (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_AD_B1_14 (coord G12), OLED */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CLK_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_CLK_GPIO_PIN                                          30U   /*!< GPIO pin number */
#define BOARD_INITPINS_CLK_GPIO_PIN_MASK                             (1U << 30U)   /*!< GPIO pin mask */

/* GPIO_AD_B1_13 (coord H11), OLED */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOSI_GPIO                                           GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MOSI_GPIO_PIN                                         29U   /*!< GPIO pin number */
#define BOARD_INITPINS_MOSI_GPIO_PIN_MASK                            (1U << 29U)   /*!< GPIO pin mask */

/* GPIO_AD_B1_04 (coord L12), BAT */

/* GPIO_B0_09 (coord C9), LED */

/* GPIO_AD_B1_00 (coord J11), IIC */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SCL_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SCL_GPIO_PIN                                          16U   /*!< GPIO pin number */
#define BOARD_INITPINS_SCL_GPIO_PIN_MASK                             (1U << 16U)   /*!< GPIO pin mask */

/* GPIO_AD_B1_01 (coord K11), IIC */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SDA_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SDA_GPIO_PIN                                          17U   /*!< GPIO pin number */
#define BOARD_INITPINS_SDA_GPIO_PIN_MASK                             (1U << 17U)   /*!< GPIO pin mask */

/* GPIO_B1_02 (coord C11), LCDIF_D14 */

/* GPIO_AD_B0_12 (coord K14), CON */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
